---
output:
  pdf_document
header-includes: \usepackage{color}
---

STAT430 Homework #4: Due Friday, February 21, 2020. 
========================================================

#### Name: KEY

*********************************************************************************

Submit this homework as a pdf file to Canvas.  I have created boxes after each problem for you to write you solution.




# Question 1
Let $Y$ have a probability density function
$$ f_Y(y) = \frac{2(\theta-y)}{\theta^2}, \hspace{.4in} 0 < y < \theta.$$

a) Find the cumulative distribution function (cdf) of $Y$. 

\textcolor{red}{
\begin{align*}
F_Y(y) &= P(Y \leq y) \\
&= \int_{-\infty}^{y} \frac{2(\theta - y)}{\theta^2}I(0<y<\theta) dy \\
&= \int_{0}^{y} \frac{2(\theta - y)}{\theta^2} dy \\
&= - \frac{2(\theta - y^2)}{2\theta^2} \Big|_{0}^y \\
&= \frac{\theta}{\theta^2} - \frac{\theta - y^2}{\theta^2}, \quad 0 < y < \theta \\
&= \frac{y^2}{\theta^2}, \quad 0 < y < \theta
\end{align*}
}

b) Show that $Y/\theta$ is a pivot.

\textcolor{red}{
Let $X = Y/\theta$ with support ${\cal X} = \{x: 0 < x < 1\}$. Then
\begin{align*}
F_X(x) &= P(X \leq x) = P(Y/\theta \leq x) = P(Y \leq \theta x) \\
&= \int_{0}^{\theta x} \frac{2(\theta - y)}{\theta^2} dy \\
&= - \frac{2(\theta - y^2)}{2\theta^2} \Big|_{0}^{\theta x} \\
&= \frac{\theta}{\theta^2} - \frac{\theta - \theta^2 x^2}{\theta^2}, \quad 0 < x < 1 \\
&= x^2, \quad 0 < x < 1
\end{align*}
Neither the distribution of $X$ nor the support of $X$ depends on $\theta$, so $X = Y/\theta$ is a pivotal quantity.
}

c) Use the pivotal quantity to create \underline{three} different 90\% confidence intervals for $\theta$.

\textcolor{red}{
We can use the pivot $Y/\theta$ to find $P(a\leq Y/\theta \leq b) = 0.90$. Consider $\alpha = 1 - 0.9 = 0.1$. We can distribute this quantity to either side of the confidence interval in any way we want. For example, let 0.05 probability be on the left side of the interval and 0.05 probability be on right side. Then we compute:
\begin{align*}
0.05 &= P(X \leq a) 
= F_X(a) 
= a^2.
\end{align*}
So $a = \sqrt{0.05}$. Now we can find $b$ in a similar manner:
\begin{align*}
0.95 &= P(X \leq b) = F_{X}(b) = b^2.
\end{align*}
So $b = \sqrt{0.95}$
Now we have that the probability $Y/\theta \geq \sqrt{0.05}$ and $Y/\theta \leq \sqrt{0.95}$ is 0.90. Solving the inequalities for $\theta$, we get that there is a 0.90 probability that
$$\theta \leq Y/\sqrt{0.05} \quad \text{ and } \quad \theta \geq Y/\sqrt{0.95}.$$
So a 90\% confidence interval for $\theta$ is $(Y/\sqrt{0.95}, Y/\sqrt{0.05})$. 
$$ $$
Note that the 90\% does NOT refer to the probability that $\theta$ is in this interval. It refers to the probability of obtaining a value $y$ such that $y/\sqrt{0.95}$ is less than $\theta$ and $y/\sqrt{0.05}$ is greater than $\theta$.
}

d) Provide a 90\% confidence interval for $\theta^2$.

# Question 2
Suppose $Y_1,...,Y_n$ are i.i.d. $N(\mu,\sigma^2)$.  Define $$\overline{Y} = \frac{1}{n} \sum_{i=1}^n Y_i \hspace{.4in} \widetilde{Y} = \frac{1}{n-1}  \sum_{i=2}^n Y_i \hspace{.4in} S^2 = \frac{1}{n-1}  \sum_{i=1}^n (Y_i- \overline{Y})^2 \hspace{.4in} \widetilde{S}^2 = \frac{1}{n-2} \sum_{i=2}^n (Y_i- \widetilde{Y})^2.$$  For each of the following, state the distribution of the quantity, whether the quantity is a pivot, and if the quantity be used to create a confidence interval for $\mu$.

a) $\overline{Y}$ \textcolor{red}{ $\sim N(\mu, \sigma^2/n)$. This is not a pivot since the distribution of the quantity depends on the parameters.}

b) $(\overline{Y} - \mu)/\sigma$ \textcolor{red}{ $\sim N(0,1/n)$. This is a pivotal quantity since the distribution does not depend on the parameters.}

c) $(\overline{Y} - \mu)/(\sigma/\sqrt{n})$ \textcolor{red}{ $\sim N(0,1)$. This is a pivot.}

d) $(\overline{Y} - \mu)/(S/\sqrt{n})$  \textcolor{red}{ $\sim t_{n-1}$. This is a pivot.}

e) $(Y_1 - \mu)/\sigma$ \textcolor{red}{ $\sim N(0, 1)$. This is a pivot.}

f) $(Y_1 - \mu)/\widetilde{S}$ \textcolor{red}{ $\sim N(0, 1/\sqrt{n-1})$. This is a pivot.}

\textcolor{red}{Note that $\widetilde{Y}$ is the sample mean of $n-1$ independent, identically distributed random variables and $\widetilde{S}^2$ is the sample variance of the same $n-1$ iid random variables.}

\newpage

# Question 3
The quality of computer disks is measured by the number of missing pulses. Brand X is such that 80% of the disks have no missing pulses. In this problem we will investigate the probability that 15 or more contain missing pulses if 100 disks of brand X are inspected. 

a) Approximate this probability using the CLT and a continuity correction.

b) Calculate the exact probability using `R`.

*********************************************************************************

**Answer:**



*********************************************************************************

