---
output:
  pdf_document: 
    extra_dependencies: ["bbm", "dsfont"]
  word_document: default
  html_document: default
---

\newcommand{\given}{\,|\,}
\newcommand{\trans}{^\text{T}}
\newcommand{\frechet}{Fr\'echet }
\newcommand{\matern}{Mat\'ern }
\newcommand{\ind}{\mathds{1}}
\newcommand{\iid}{\stackrel{\text{iid}}{\sim}}
\newcommand{\indep}{\stackrel{\text{indep}}{\sim}}


STAT430 Homework #8: Due Friday, April 22, 2022. 
========================================================

#### Name: 

*********************************************************************************

Submit this homework as a pdf file to Canvas. 

## Question 1

Let $Y_1,...,Y_n$ be a random sample from a Gamma($\alpha$,mean=$\beta$) distribution, where $\alpha>0$ is known.

a) Find the MLE of $\beta$.

b) Is the MLE unbiased?

c) Compute the variance of the MLE.

d) Find the MVUE of $\beta$.


*********************************************************************************

**Answer:**



*********************************************************************************


## Question 2
The number of red chips and white chips in an urn is unknown, but the proportion $p$ of reds is either $1/3$ or $1/2$.  A sample of size 5, drawn with replacement, yields the sequence R, W, W, R, W.  What is the maximum likelihood estimator for $p$?


*********************************************************************************

**Answer:**



*********************************************************************************

## Question 3

Suppose $Y_1,...,Y_n$ are i.i.d. according to density
$$f(y) = e^{-(y-\theta)}, \hspace{.5in} y \ge \theta, \hspace{.5in} \theta > 0.$$
Find the MLE of $\theta$.


*********************************************************************************

**Answer:**



*********************************************************************************

## Question 4


Suppose $Y_1,...,Y_n \sim$ i.i.d. Poisson($\lambda$).  

a) Find the MLE for $\lambda$.

b) Calculate $I(\lambda)$.

c) Calculate $I_n(\lambda)$.  

d) What is the CRLB for estimating $\lambda$ based on $Y_1,...,Y_n$?

e) What is the asymptotic distribution of the MLE, $\hat{\lambda}$?

f) Use R to simulate $1,000$ iid Poisson datasets, each with $\lambda=3$ and $n=20$.  For each simulated dataset, compute the MLE for $\lambda$ and use your answer in part e) to construct a 95% confidence interval for $\lambda$.  What percentage  of your confidence intervals included $\lambda$?  How close is the variance of your MLEs to the asymptotic variance reported in part e)?  Plot a qq-plot of your appropriately standardized MLEs vs. the quantiles of a standard normal distribution.

g) Repeat part f) with $n=50$.

*********************************************************************************

**Answer:**



*********************************************************************************

