---
title: "STAT 620 Homework 6"
author: "Hannah Butler"
date: "3/4/2022"
header-includes:
  - \usepackage{mathrsfs}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. (5.12) Let $\mathbb{X} = \{1,2,3\}$ let $\nu$ be a set function on $\mathscr{P}_{\mathbb{X}}$. with values $\nu(\emptyset) = 0$ and $\nu(\{1,2,3\}) = 1$. Set $x = \nu(\{1,2\})$, $y = \nu(\{2,3\})$, and $z = \nu(\{1,3\})$. Find necessary and sufficient conditions on $x,y$, and $z$ such that it is possible for $\nu$ to be additive.

We must have that
\begin{align*}
\nu(\{1\}) + \nu(\{2\}) &= x, \\
\nu(\{2\}) + \nu(\{3\}) &= y, \text{ and} \\
\nu(\{1\}) + \nu(\{3\}) &= z
\end{align*}

also, we must have
$$\nu(\{1\}) + \nu(\{2\}) + \nu(\{3\}) = \nu(\{1,2,3\}) = 1.$$
Solving for $\nu(\{1\})$, $\nu(\{2\})$, $\nu(\{3\})$, respectively, we have
\begin{align*}
\nu(\{1\}) &= x - \nu(\{2\}), \\
\nu(\{2\}) &= y - \nu(\{3\}), \\
\nu(\{3\}) &= z - \nu(\{1\}).
\end{align*}

Plugging these in, we see that
\begin{align*}
1 &= (x - \nu(\{2\})) + (y - \nu(\{3\})) + (z - \nu(\{1\})) \\
&= x + y + z - (\nu(\{1\}) + \nu(\{2\}) + \nu(\{3\})) \\
&= x+ y + z - 1
\end{align*}
So we have that $x + y + z = 2$ as a necessary and sufficient condition for $\nu$ to be an additive measure. It is sufficient, since this condition was found on the basis that all subsets of 2 and 3 are additive.

2. (5.14) Let $\mathbb{X}$ be a nonempty set and fix $x \in \mathbb{X}$. Define 
$$\mu^*(A) = \begin{cases} 1, & x\in A \\ 0, & x\notin A \end{cases}$$
for $A \subset \mathbb{X}$. Prove that $\mu^*$ is an outer measure, and describe the collection ${\cal M}$ of $\mu^*$-measurable sets.

To show that $\mu^*$ is an outer measure, we must show that $\mu^*(\emptyset)=0$, monotonicity, and sub-additivity. 

Since $\emptyset$ is in fact, empty, $x \notin \emptyset$. So $\mu^*(\emptyset) = 0$.

To show monotonicity, let $A \subset B \in \mathscr{P}_{\mathbb{X}}$. If $x \in A$, then $x \in B$ and $1=\mu^*(A) = \mu^*(B)$. Similarly, if $x \notin A$, then $x$ may or may not be in $B$. if $x\notin B$, then $0 = \mu*(A) = \mu^*(B)$. If $x \in B$, then $\mu^*(A) < \mu^*(B) = 1$. In any case $\mu^*(A) \leq \mu^*(B)$.

Finally, to show subadditivity, let $\{ A_i \}_{i=1}^\infty$ be a collection of sets in $\mathscr{P}_{\mathbb{X}}$ and let $x$ be an element of $\bigcup_{i=1}^\infty A_i$. Then $\mu^*\left(\bigcup_{i=1}^\infty A_i \right) = 1.$ However, if $x \in \bigcup_{i=1}^\infty A_i$, then $x$ is an element of at least one of the $A_i$, so $1 = \mu^*\left(\bigcup_{i=1}^\infty A_i \right) \leq \sum_{i=1}^\infty \mu^*(A_i)$. If $x$ is not an element of $\bigcup_{i=1}^\infty A_i$, then $\mu^*\left(\bigcup_{i=1}^\infty A_i\right) = 0$. Additionally, $x$ can not an element of any $A_i$, so $\sum_{i=1}^\infty \mu^*(A_i) = 0$ as well. This still satisfies sub-additivity, so $\mu^*$ is a sub-additive measure.

The set of $\mu^*$-measurable sets are those sets $A$ that satisfy
$$\mu^*(E) = \mu^*(E \cap A) + \mu^*(E \cap A^c).$$
For all sets $E$ in $\mathscr{P}_{\mathbb{X}}$. 
For any set in $\mathscr{P}_{\mathbb{X}}$, $x$ is either an element of the set or an element of the compliment. If $x$ is not in a set $E$, then $\mu^*(E) = \mu^*(E\cap A) = \mu^*(E \cap A^c) = 0$ and $\mu^*(E) = \mu^*(E \cap A) + \mu^*(E \cap A^c)$. Otherwise, if $x$ is in $E$, then $\mu^*(E) = 1$. In this case $x$ is in exactly one of $E\cap A$ or $E\cap A^c$, so $\mu^*(E \cap A) + \mu^*(E \cap A^c) = 1$ as well. This holds for all sets in $\mathscr{P}_{\mathbb{X}}$, so all subsets of $\mathbb{X}$ are $\mu^*$-outer measurable.

3. (5.17) on $\mathbb{X} = \mathbb{N}$, define the set function $\nu:\mathscr{P}_{\mathbb{X}} \to [0,\infty]$ by 
$$\nu(A) = \begin{cases} \sum_{i\in A} \frac{1}{2^i} & A \text{ finite} \\ \infty & A \text{ infinite}. \end{cases}$$
for $A \in \mathscr{P}_{\mathbb{X}}.$

  * Prove that $\nu$ is finitely additive but not countably additive.
  * Compute $\mu^*_\nu$ and the collection ${\cal M}$ of $\mu^*_\nu$- measurable sets
  * Show that $\nu \neq \mu^*_\nu$.
  
  Let $\{A_i\}_{i=1}^n$ be a finite collection of disjoint sets in $\mathscr{P}_{\mathbb{X}}$. If any of the $A_i$ are infinite, then $\bigcup_{i=1}^n A_i$ is infinite and $\nu\left(\bigcup_{i=1}^n A_i \right) = \sum_{i=1}^n A_i = \infty$, since adding any positive value to $\infty$ is still $\infty$. If every set in the collection is finite, then $\nu\left(\bigcup_{i=1}^n A_i \right) = \sum_{i\in \cup A_i}\frac{1}{2^i} = \sum_{i\in A_1}\frac{1}{2^i} + \sum_{i\in A_2}\frac{1}{2^i} + \dots + \sum_{i\in A_n}\frac{1}{2^i} = \sum_{i=1}^n \nu(A_i)$, since the $A_i$ are disjoint. 
  
  Consider, on the other hand, the countable collection of set $\{A_i\}_{i=1}^\infty$ where $A_i = \{ i \}$. Then $\nu(\bigcup A_i) = \infty$, since $\bigcup A_i$ is infinite. but $\sum_{i=1}^\infty \nu(A_i) = \sum_{i=1}^\infty \frac{1}{2^i} = 1$. So $\nu$ is not countably additive.
  
  Using Theorem 5.4.3, we can construct an outer measure using the set function $\nu$:
  $$\mu^*_\nu(A) = \inf\left\{ \sum_{i=1}^\infty \nu(A_i) : \{A_i\} \subset \mathscr{P}_{\mathbb{X}} \text{ and } A \subset \bigcup_{i=1}^\infty A_i \right\}.$$
  
  
  