---
title: "620 Homework 4"
author: "Hannah Butler"
date: "2/28/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. (Exercise 4.2) Show that every point in the Cantor set ${\cal C}$ is the limit of a sequence of points in ${\cal C}$. 

***

According to **Principles of Mathematical Analysis** (Rudin), "A point $p$ is a limit point of the set $E$ if every neighborhood of $p$ contains a point $q\neq p$ such that $q\in E$."

So, let $p$ be a point in ${\cal C}$. Then $p \in \bigcap_{i=0}^\infty F_i$, where $F_i$ is a finite union of $2^i$ closed intervals (as defined in the class notes). Then $p$ must be in all $F_i$ for $i = 0, 1, 2, \dots$ so that $p$ is always contained in a closed interval of length $1/3^i$. Then for every neighborhood $N$, of $p$, there is a point $q \in N$ that is also in that same interval. So $p$ is a limit point. 

2. (Exercise 4.3) Show that the cantor set does not contain any open intervals. 

***

Using another result from **Principles of Mathematical Analysis**, we have the following Lemma: *For any collection $\{F_\alpha\}$ of closed sets, $\bigcap_\alpha F_\alpha$ is closed. We also have that for any finite collection of closed sets, the union of these sets is closed.* 
(I know I should prove this, but I'm just trying to get this homework done.)

Since $F_i$ is a finite union of closed sets, $F_i$ must also be closed, and since ${\cal C}$ is an (infinite) intersection of closed sets, ${\cal C}$ is also closed.

3. (Exercise 4.4) Prove Theorem 4.3.3: *${\cal D}$ is a bounded function, ${\cal D} = 0$ a.e., and ${\cal D}(x)$ is not continuous a.e.*

***

${\cal D}(x)$ is bounded by 1, since for all $x \in \mathbb{R}$, the value of ${\cal D}$ never exceeds 1.

To show that ${\cal D}(x) = 0$ almost everywhere, we need to show that ${\cal D}(x) \neq 0$ only on a set of measure zero: 

We know that a single point has measure zero, and ${\cal D}(x) = 1$ only for $x \in \mathbb{Q}$, which is a countable set of points. Therefore, by Theorem 4.3.1, the set where ${\cal D}(x) = 1$ is a set of measure zero.

Finally, to show that ${\cal D}(x)$ is not continuous almost everywhere, we need to show that ${\cal D}(x)$ is continuous only on a set of measure zero:

First, ${\cal D}$ is continuous at $x_0$ if, given $\delta > 0$, there exists an $\epsilon > 0$ such that $|{\cal D}(x) - {\cal D}(x_0)| < \delta$ for any $x$ such that $|x - x_0| < \epsilon$. However, given $x_0 \notin \mathbb{Q}$, there is no $\epsilon$ neighborhood around $x_0$ that does not contain an $x \in \mathbb{Q}$, so for $\delta < 1$, we can not have $|{\cal D}(x) - {\cal D}(x_0)| < \delta$ for any $\epsilon$. Therefore, ${\cal D}$ is only continuous on, at most, a set of measure zero ($\mathbb{Q}$). (I think, by the same reasoning, ${\cal D}$ is also not continuous on $\mathbb{Q}$.)